"use client";
import { useState } from "react";
import JsxParser from "react-jsx-parser";

const HomePage = () => {
  const [prompt, setPrompt] = useState("");
  const [code, setCode] = useState("");

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      alert("Code copied to clipboard");
    } catch (error) {
      console.error("Failed to copy: ", error);
    }
  };

  const handleGenerate = async () => {
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ body: prompt }),
      });

      const data = await response.json();
      if (response.ok) {
        setCode(data.code);
      } else {
        console.error("Error:", data.error);
      }
    } catch (error) {
      console.error("Fetch error:", error);
    }
  };

  return (
    <div className="flex flex-col min-h-screen">
    <main className="flex min-h-screen flex-col items-center p-12 flex-grow">
      <div className="max-w-5xl w-full flex-col items-center justify-center text-sm lg:flex">
        <p className="text-5xl mb-4 font-bold bg-gradient-to-r from-purple-600 to-pink-600 text-transparent bg-clip-text">
          UI Nova
        </p>
        <div className="relative flex items-center w-full h-12 rounded-lg focus-within:shadow-md overflow-hidden">
          <input
            className="peer h-full w-full outline-none bg-gray-100 text-sm text-gray-700 pl-4 pr-12"
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Enter a prompt to get the modern UI"
          />
          <div className="absolute right-0 flex items-center justify-center h-full w-12 bg-purple-500 hover:bg-blue-600 text-white cursor-pointer">
            <p className="text-2xl" onClick={handleGenerate}>
              ➔
            </p>
          </div>
        </div>

        <div className="flex">
          <button
            onClick={handleCopy}
            className="bg-purple-500 rounded text-white px-5 py-3 mt-7 hover:bg-blue-600 m-4"
          >
            Copy Code
          </button>
          <button
            onClick={handleGenerate}
            className="bg-purple-500 rounded text-white px-5 py-3 mt-7 hover:bg-blue-600 m-4"
          >
            Refresh
          </button>
        </div>

        <div className="mt-7 p-2 flex justify-center text-black text-base">
          <JsxParser jsx={code} />
        </div>

        {/* Disclaimer Section */}
        <div className={`${code=="" ? 'mt-20' : 'mt-10' } p-4 bg-transparent-50 rounded-lg text-sm text-gray-600`}>
          <h3 className="font-semibold mb-2 text-xl">Disclaimer</h3>
          <p className="mb-3">
            The code generated by UI Nova is provided "as is" without warranty of any kind. 
            While we strive to generate high-quality, functional UI components, users should 
            review and test all generated code before implementation in production environments.
          </p>
          <p className="mb-3">
            The UI code preview generated by the UI Nova is only for visual purpose. The actual UI look better when the code is implemented in the desired place. 
          </p>
        </div>

        {/* Contact and Copyright Section */}
        <footer className="mt-1 pt-3 border-t border-gray-200">
          <div className="text-center text-gray-600 text-sm">
            <div className="mb-2">
              <h4 className="font-semibold mb-1">Contact Us</h4>
              <p>
                Email:{" "}
                <a 
                  href="mailto:b24127@students.iitmandi.ac.in"
                  className="text-purple-600 hover:text-purple-800 hover:underline"
                >
                  b24127@students.iitmandi.ac.in
                </a>
              </p>
              <p>
                GitHub:{" "}
                <a 
                  href="https://github.com/harshyadav028"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-purple-600 hover:text-purple-800 hover:underline"
                >
                  github.com/harshyadav028
                </a>
              </p>
            </div>
            <div className="mt-4">
              <p>© {new Date().getFullYear()} UI Nova. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </div>
    </main>
    </div>
  );
};

export default HomePage;